version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 327512371512.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-app .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker tag brain-app:latest 327512371512.dkr.ecr.ap-south-1.amazonaws.com/brain-app:latest
      - docker push 327512371512.dkr.ecr.ap-south-1.amazonaws.com/brain-app:latest
